django-assignment/taskmanager/orm/urls.py
from django.urls import path
from .views import (
    UserProfileListView, UserProfileDetailView, UserProfileCreateView,
    ProductListView, ProductDetailView, ProductCreateView
)

urlpatterns = [
    path('userprofiles/', UserProfileListView.as_view(), name='userprofile-list'),
    path('userprofiles/<int:pk>/', UserProfileDetailView.as_view(), name='userprofile-detail'),
    path('userprofiles/create/', UserProfileCreateView.as_view(), name='userprofile-create'),

    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/create/', ProductCreateView.as_view(), name='product-create'),
]

django-assignment/taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('task-manager/', include('home.urls')),
    path('orm/', include('orm.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-assignment/taskmanager/orm/models.py
from django.db import models


class UserProfile(models.Model):
    GENDER_MALE = 'M'
    GENDER_FEMALE = 'F'
    GENDER_CHOICES = [
        (GENDER_MALE, 'Male'),
        (GENDER_FEMALE, 'Female')
    ]
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.IntegerField(default=0)
    birth_date = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=GENDER_MALE)
    

class User(models.Model):
    username = models.CharField(max_length=15)
    user_info = models.OneToOneField(UserProfile, null=True, on_delete=models.SET_NULL)


class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    
class Tag(models.Model):
    tag_name = models.CharField(max_length=100)

class Product(models.Model):
    product_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_image = models.ImageField(upload_to='product-images/', null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name
    

django-assignment/taskmanager/orm/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import UserProfile, Product

class UserProfileListView(View):
    def get(self, request):
        userprofiles = UserProfile.objects.select_related('user').all()
        return render(request, 'userprofile_list.html', {'userprofiles': userprofiles})

class UserProfileDetailView(View):
    def get(self, request, pk):
        userprofile = UserProfile.objects.select_related('user').get(pk=pk)
        return render(request, 'userprofile_detail.html', {'userprofile': userprofile})

class UserProfileCreateView(View):
    def get(self, request):
        return render(request, 'userprofile_form.html')

    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        birth_date = request.POST.get('birth_date')
        gender = request.POST.get('gender')
        
        userprofile = UserProfile.objects.create(
            name=name,
            email=email,
            phone=phone,
            birth_date=birth_date,
            gender=gender
        )
        return redirect('userprofile-detail', pk=userprofile.pk)

class ProductListView(View):
    def get(self, request):
        products = Product.objects.select_related('category').prefetch_related('tags').all()
        return render(request, 'product_list.html', {'products': products})

class ProductDetailView(View):
    def get(self, request, pk):
        product = Product.objects.select_related('category').prefetch_related('tags').get(pk=pk)
        return render(request, 'product_detail.html', {'product': product})

class ProductCreateView(View):
    def get(self, request):
        return render(request, 'product_form.html')

    def post(self, request):
        product_name = request.POST.get('product_name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        category_id = request.POST.get('category')
        product_image = request.FILES.get('product_image')
        tag_ids = request.POST.getlist('tags')
        
        product = Product.objects.create(
            product_name=product_name,
            price=price,
            description=description,
            category_id=category_id,
            product_image=product_image
        )
        product.tags.add(*tag_ids)
        return redirect('product-detail', pk=product.pk)

django-assignment/taskmanager/orm/templates/base2.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Website{% endblock %}</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'userprofile-list' %}">User Profiles</a></li>
            <li><a href="{% url 'product-list' %}">Products</a></li>
        </ul>
    </nav>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

django-assignment/taskmanager/orm/templates/product_detail.html
{% extends 'base2.html' %}

{% block title %}Product Detail{% endblock %}

{% block content %}
    <h1>Product Detail</h1>
    <p><strong>Name:</strong> {{ product.product_name }}</p>
    <p><strong>Price:</strong> ${{ product.price }}</p>
    <p><strong>Description:</strong> {{ product.description }}</p>
    <p><strong>Category:</strong> {{ product.category.category_name }}</p>
    <p><strong>Tags:</strong>
        {% for tag in product.tags.all %}
            {{ tag.tag_name }}
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <a href="{% url 'product-list' %}">Back to Products</a>
{% endblock %}

django-assignment/taskmanager/orm/templates/product_form.html
{% extends 'base2.html' %}

{% block title %}Create Product{% endblock %}

{% block content %}
    <h1>Create Product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="product_name">Product Name:</label>
        <input type="text" id="product_name" name="product_name"><br>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" step="0.01"><br>
        <label for="description">Description:</label>
        <textarea id="description" name="description"></textarea><br>
        <label for="category">Category:</label>
        <select id="category" name="category">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.category_name }}</option>
            {% endfor %}
        </select><br>
        <label for="product_image">Product Image:</label>
        <input type="file" id="product_image" name="product_image"><br>
        <label for="tags">Tags:</label>
        <select id="tags" name="tags" multiple>
            {% for tag in tags %}
                <option value="{{ tag.id }}">{{ tag.tag_name }}</option>
            {% endfor %}
        </select><br>
        <button type="submit">Create</button>
    </form>
    <a href="{% url 'product-list' %}">Cancel</a>
{% endblock %}

django-assignment/taskmanager/orm/templates/product_list.html
{% extends 'base2.html' %}

{% block title %}Products{% endblock %}

{% block content %}
    <h1>Products</h1>
    <ul>
        {% for product in products %}
            <li><a href="{% url 'product-detail' product.pk %}">{{ product.product_name }}</a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'product-create' %}">Create New Product</a>
{% endblock %}

django-assignment/taskmanager/orm/templates/userprofile_detail.html
{% extends 'base2.html' %}

{% block title %}User Profile Detail{% endblock %}

{% block content %}
    <h1>User Profile Detail</h1>
    <p><strong>Name:</strong> {{ userprofile.name }}</p>
    <p><strong>Email:</strong> {{ userprofile.email }}</p>
    <p><strong>Phone:</strong> {{ userprofile.phone }}</p>
    <p><strong>Birth Date:</strong> {{ userprofile.birth_date }}</p>
    <p><strong>Gender:</strong> {{ userprofile.get_gender_display }}</p>
    <a href="{% url 'userprofile-list' %}">Back to User Profiles</a>
{% endblock %}

django-assignment/taskmanager/orm/templates/userprofile_list.html
{% extends 'base2.html' %}

{% block title %}User Profiles{% endblock %}

{% block content %}
    <h1>User Profiles</h1>
    <ul>
        {% for userprofile in userprofiles %}
            <li><a href="{% url 'userprofile-detail' userprofile.pk %}">{{ userprofile.name }}</a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'userprofile-create' %}">Create New User Profile</a>
{% endblock %}